// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rvvlpvwzrwadgvvmsoki.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ2dmxwdnd6cndhZGd2dm1zb2tpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1NzI2MjgsImV4cCI6MjA3MzE0ODYyOH0.k2z69KhMxd5M-9Z90ZHSq7WtHK4JUNr7z_E08QfZT_I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});